version: '3'

services:
  db-mysql:
    container_name: db-mysql
    image: "ktchae/mysql:0.0.1"
    ports:
      - "3306:3306"
      - "33060:33060"
    environment:
      - MYSQL_ROOT_PASSWORD=qordpsem!
      - MYSQL_DATABASE=calculator
  app01:
    container_name: app01
    depends_on:
      - db-mysql
    links:
      - db-mysql
    image: "ktchae/calc:0.0.8"
    ports:
      - "8888:8080"
  app02:
    container_name: app02
    depends_on:
      - db-mysql
    links:
      - db-mysql
    image: "ktchae/calc:0.0.8"
    ports:
      - "8889:8080"
#  nginx-test:
#    container_name: nginx-test
#    image: "ktchae/nginx:0.0.3"
#    ports:
#      - "80:80"
#    depends_on:
#      - app01
#      - app02
#    links:
#      - app01
#      - app02