version: '3'

services:
  db-mysql:
    container_name: db-mysql
    image: "ktchae/mysql:0.0.1"
    ports:
      - "3306:3306"
      - "33060:33060"
    environment:
      - MYSQL_ROOT_PASSWORD=qordpsem!
      - MYSQL_DATABASE=calculator
  app01:
    container_name: app01
    depends_on:
      - db-mysql
    links:
      - db-mysql
    image: "ktchae/calc:0.0.7"
    ports:
      - "8888:8080"
  app02:
    container_name: app02
    depends_on:
      - db-mysql
    links:
      - db-mysql
    image: "ktchae/calc:0.0.7"
    ports:
      - "8889:8080"