spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create  # (1) 스키마 자동 생성
    show-sql: true      # (2) SQL 쿼리 출력
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


server:
  ssl:
    key-store: classpath:localhost.p12
    key-store-type: PKCS12
    key-store-password: changeit

logging:
  file:
    max-history: 999999
    max-size: 5MB
    name: ./logs/calc_service.log
  pattern:
    console: "[%-5level] [%d{yyyy-MM-dd HH:mm:ss}][%thread] [%F - %M] [%logger{0}:%line] - %msg%n"
    file: "[%-5level] [%d{yyyy-MM-dd HH:mm:ss}][%thread] [%F - %M] [%logger{0}:%line] - %msg%n"