spring:
#  h2:
#    console:
#      enabled: true
#      path: /h2
  datasource:
#    url: jdbc:h2:mem:test
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db-mysql:3306/calculator?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: qordpsem!
  jpa:
    hibernate:
      ddl-auto: update  # (1) 스키마 자동 생성
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true      # (2) SQL 쿼리 출력
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


server:
  ssl:
    key-store: classpath:localhost.p12
    key-store-type: PKCS12
    key-store-password: changeit

logging:
  file:
    max-history: 999999
    max-size: 5MB
    name: ./logs/calc_service.log
  pattern:
    console: "[%-5level] [%d{yyyy-MM-dd HH:mm:ss}][%thread] [%F - %M] [%logger{0}:%line] - %msg%n"
    file: "[%-5level] [%d{yyyy-MM-dd HH:mm:ss}][%thread] [%F - %M] [%logger{0}:%line] - %msg%n"